# ==========================================
# Base Infrastructure
# ==========================================

resource "azurerm_resource_group" "rg" {
  name     = var.resource_group_name
  location = var.location
}

# ==========================================
# Cognitive Services & AI Search
# ==========================================

resource "azurerm_cognitive_account" "openai" {
  name                = var.openai_account_name
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  kind                = "OpenAI"
  sku_name            = "S0"

  # Enforce Entra ID authentication for Zero-Trust compliance
  local_auth_enabled    = false
  custom_subdomain_name = var.openai_account_name
}

resource "azurerm_search_service" "search" {
  name                = var.search_service_name
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  sku                 = "standard"

  local_authentication_enabled = false
}

# ==========================================
# Shared Private Link Automation
# ==========================================

resource "azurerm_search_shared_private_link_service" "openai_link" {
  name              = "rag-openai-link"
  search_service_id = azurerm_search_service.search.id

  subresource_name = "openai_account"

  target_resource_id = azurerm_cognitive_account.openai.id
  request_message    = "Auto-generated by Terraform"
}

# ==========================================
# THE MAGIC: AzAPI Auto-Approve Workaround
# ==========================================

# 1. We query the dynamically generated Private Endpoint Connection ID
data "azapi_resource_list" "pe_connections" {
  type                   = "Microsoft.CognitiveServices/accounts/privateEndpointConnections@2023-05-01"
  parent_id              = azurerm_cognitive_account.openai.id
  response_export_values = ["value"]

  depends_on = [
    azurerm_search_shared_private_link_service.openai_link
  ]
}

# 2. We dynamically filter for the 'Pending' connection and approve it
resource "azapi_update_resource" "approve_shared_link" {
  type = "Microsoft.CognitiveServices/accounts/privateEndpointConnections@2023-05-01"

  # Extracts the exact resource_id of the pending connection
  resource_id = try([for conn in jsondecode(data.azapi_resource_list.pe_connections.output).value : conn.id if conn.properties.privateLinkServiceConnectionState.status == "Pending"][0], "")

  body = jsonencode({
    properties = {
      privateLinkServiceConnectionState = {
        status      = "Approved"
        description = "Approved via Terraform AzAPI Pipeline"
      }
    }
  })
}
